server:
  port: 8082

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost:3306/jobs_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    function:
      definition: updateCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: job-created-events
        updateCommunication-in-0:
          destination: job-communication-sent
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: job-service
    description: Zapp_Mini Job Service Application
    version: 1.0.0


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
