global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'client-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['client-service:8081']
  - job_name: 'job-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'job-service:8082' ]
  - job_name: 'candidate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'candidate-service:8083' ]
  - job_name: 'message-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'message-service:8085' ]
  - job_name: 'eureka-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-service:8070' ]
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-service:8072' ]