server:
  port: 8085

spring:
  application:
    name: message-service
  cloud:
    function:
      definition: jobCreatedEmail|jobCreatedSms; candidateAddedEmail|candidateAddedSms; candidateStatusChanged
    stream:
      bindings:
        # 🔹 Job Created Bindings
        jobCreatedEmailjobCreatedSms-in-0:
          destination: job-created-events
          group: ${spring.application.name}
        jobCreatedEmailjobCreatedSms-out-0:
          destination: job-communication-sent

        # 🔹 Candidate Added Bindings
        candidateAddedEmailcandidateAddedSms-in-0:
          destination: candidate-added-events
          group: ${spring.application.name}
        candidateAddedEmailcandidateAddedSms-out-0:
          destination: candidate-communication-sent

        # 🔹 Candidate Status Changed Binding (single input/output)
        candidateStatusChanged-in-0:
          destination: candidate-status-events
          group: ${spring.application.name}
        candidateStatusChanged-out-0:
          destination: candidate-status-communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      zapp:
        message_service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
