server:
  port: 8083

spring:
  application:
    name: candidate-service
  datasource:
    url: jdbc:mysql://localhost:3306/candidate_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: candidate-service
    description: Zapp_Mini Candidate Service Application
    version: 1.0.0


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
