server:
  port: 8083

spring:
  application:
    name: candidate-service
  datasource:
    url: jdbc:mysql://localhost:3306/candidate_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    function:
      definition: updateCommunication;updateStatusCommunication
    stream:
      bindings:
        # 🔹 Candidate Added Event (output)
        sendCommunication-out-0:
          destination: candidate-added-events

        # 🔹 Candidate Added Communication Acknowledgment (input)
        updateCommunication-in-0:
          destination: candidate-communication-sent
          group: ${spring.application.name}

        # 🔹 Candidate Status Changed Event (output)
        sendStatusCommunication-out-0:
          destination: candidate-status-events

        # 🔹 Candidate Status Communication Acknowledgment (input)
        updateStatusCommunication-in-0:
          destination: candidate-status-communication-sent
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    connection-timeout: 10s


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 1
      limitRefreshPeriod: 5000
      timeoutDuration: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: candidate-service
    description: Zapp_Mini Candidate Service Application
    version: 1.0.0


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
