server:
  port: 8072

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      zapp:
        gateway_service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  app:
    name: "gateway-service"
    description: "Zapp-Hrms Gateway server application"
    version: "1.0.0"

springdoc:
  swagger-ui:
    urls:
      - name: CLIENT-SERVICE
        url: /zapphrms/client-service/v3/api-docs
      - name: JOB-SERVICE
        url: /zapphrms/job-service/v3/api-docs
      - name: CANDIDATE-SERVICE
        url: /zapphrms/candidate-service/v3/api-docs
      - name: USER-SERVICE
        url: /zapphrms/user-service/v3/api-docs

