
deploymentName: clients-deployment
serviceName: client-service
appLabel: client-service
appName: client-service

replicaCount: 1

image:
  repository: ramjee92/client-service
  tag: s11

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false